### ISSUE TITLE
UnboundLocalError: local variable 'streams' referenced before assignment

### ISSUE THREAD

**Issue by jlloyd-widen** [anelendata/tap-rest-api#22]
Using this tap within a Meltano pipeline. I'm trying to run `meltano select --list --all tap-rest-api` but I'm getting the following error:

```
Cannot list the selected attributes: Catalog discovery failed: command ['/Users/.../meltano/.meltano/extractors/tap-rest-api/venv/bin/tap-rest-api', '--config', '/Users/.../meltano/.meltano/run/tap-rest-api/tap.config.json', '--discover'] returned 1: CRITICAL local variable 'streams' referenced before assignment
Traceback (most recent call last):
  File "/Users/.../meltano/.meltano/extractors/tap-rest-api/venv/bin/tap-rest-api", line 8, in <module>
    sys.exit(main())
  File "/Users/.../meltano/.meltano/extractors/tap-rest-api/venv/lib/python3.7/site-packages/singer/utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "/Users/.../meltano/.meltano/extractors/tap-rest-api/venv/lib/python3.7/site-packages/tap_rest_api/__init__.py", line 177, in main
    for stream in streams:
UnboundLocalError: local variable 'streams' referenced before assignment

```

Operating System: MacOS Catalina

`Meltano.yml`
```
version: 1
send_anonymous_usage_stats: false
elt.buffer_size: 52428800
plugins:
  extractors:
  - name: tap-rest-api
    pip_url: tap-rest-api
    namespace: tap_rest_api
    executable: tap-rest-api
    capabilities:
      - catalog
      - config
      - state
      - discover
    settings:
      - name: url
    config:
      url: http://<something>.com

```

**Comment by daigotanaka** [comment]
Hi @jlloyd-widen

Thx for trying out tap-rest-api. I think you need to add `schema` in config.json as in [Step 3](https://github.com/anelendata/tap-rest-api#step-3-create-config-file) in the example.

That said, the program should detect the config error and I will plan to work on better error messages.

Let me know if you need further assistance.

Thanks!

Daigo

**Comment by jlloyd-widen** [comment]
Yeah, sorry I should have update this earlier. I figured out my problem was adding `- name: schema` and `- name: streams` to `settings` within the `meltano.yml` file and then adding appropriate values in the `config` of the same tap. But I got stuck there with a different error that correlates with Step 4 in the readme. I'll submit a separate ticket for that error.
